const express = require("express");
const router = express.Router();
const controller = require("../../controllers/admin/account.controller");
const cloud = require("../../middlewares/admin/cloud.middlewares");
var multer = require('multer');
var upload = multer();
router.get("/" , controller.index);
router.get("/create" , controller.viewCreateAccount);
router.post("/create" , upload.single('avatar') , cloud.clouldMiddlewares, controller.createAccount);
module.exports = router;