const express = require("express");
const router = express.Router();
const controller = require("../../controllers/admin/account.controller");
const cloud = require("../../middlewares/admin/cloud.middlewares");
var multer = require('multer');
var upload = multer();
router.get("/" , controller.index);
router.get("/create" , controller.viewCreateAccount);
router.post("/create" , upload.single('avartar') , cloud.clouldMiddlewares, controller.createAccount);
router.patch("/changeStatus/:inforChange" , controller.changeStatus);
router.delete("/delete/:id" , controller.deleteAccount);
router.get("/detel/:id" , controller.viewDetelAccount);
router.get("/edit/:id" , controller.viewEdit);
router.patch("/edit/:id" , upload.single('avartar') , cloud.clouldMiddlewares, controller.editAccount);
router.patch("/change-multi" , controller.changeMulti);
module.exports = router;