const express = require("express");
const router = express.Router();
const controller = require("../../controllers/admin/auth.controller");
const cloud = require("../../middlewares/admin/cloud.middlewares");
var multer = require('multer');
var upload = multer();
router.get("/login"  , controller.viewLogin);
router.post("/login" , controller.login);
router.get("/logout" , controller.logout);
module.exports = router;