const dashboardRouter = require("./dashboard.router");
const systemConfig = require("../../configs/systems");
const productsRouter = require("./products.router");
const dustbinProductRouter = require("./dustbinProduct.router");
const categoryRouter = require("./categorty.router");
const chatRouter = require("./chat.router");
const dustbinMessRouter = require("./dustbinMess.router");
const roleRouter = require("./role.router");
const dustbinRoleController = require("./dustbinRole.router");
const accountRouter = require("./account.router");
const authRouter = require("./auth.router.js");
const authMiddleware = require("../../middlewares/admin/auth.middleware.js");
const myAccountRouter = require("./myAccount.router.js");
const dustbinCategoryRouter = require("./dustbinCategory.router.js");
const dustbinAccountRouter = require("./dustbinAccount.router.js");
const postCategoryRouter = require("./postCategory.router.js");
const dustbinPOstCategoryRouter = require("./dustbinPostCategory.router.js");
const generalSettingRouter = require("./generalSetting.router.js");
module.exports = (app) => {
    const PATH_ADMIN = systemConfig.prefixAdmin;
    app.use(PATH_ADMIN + "/dashboard", authMiddleware.requireAuth, dashboardRouter);
    app.use(PATH_ADMIN + "/products", authMiddleware.requireAuth, productsRouter);
    app.use(PATH_ADMIN + "/dustbinProduct", authMiddleware.requireAuth, dustbinProductRouter);
    app.use(PATH_ADMIN + "/categorys", authMiddleware.requireAuth, categoryRouter);
    app.use(PATH_ADMIN + "/chat", authMiddleware.requireAuth, chatRouter);
    app.use(PATH_ADMIN + "/dustbin-mess", authMiddleware.requireAuth, dustbinMessRouter);
    app.use(PATH_ADMIN + "/role", authMiddleware.requireAuth, roleRouter);
    app.use(PATH_ADMIN + "/dustbinRole", authMiddleware.requireAuth, dustbinRoleController);
    app.use(PATH_ADMIN + "/account", authMiddleware.requireAuth, accountRouter);
    app.use(PATH_ADMIN + "/auth", authRouter);
    app.use(PATH_ADMIN + "/my-account", authMiddleware.requireAuth, myAccountRouter);
    app.use(PATH_ADMIN + "/dustbinCategory", authMiddleware.requireAuth, dustbinCategoryRouter);
    app.use(PATH_ADMIN + "/dustbinAccount", authMiddleware.requireAuth, dustbinAccountRouter);
    app.use(PATH_ADMIN + "/postCategory", authMiddleware.requireAuth, postCategoryRouter);
    app.use(PATH_ADMIN + "/dustbinPostCategory", authMiddleware.requireAuth, dustbinPOstCategoryRouter);
    app.use(PATH_ADMIN + "/general-setting", authMiddleware.requireAuth, generalSettingRouter);
};