const dashboardRouter = require("./dashboard.router");
const systemConfig = require("../../configs/systems");
const productsRouter = require("./products.router");
const dustbinProductRouter = require("./dustbinProduct.router");
const categoryRouter = require("./categorty.router");
const chatRouter = require("./chat.router");
const dustbinMessRouter = require("./dustbinMess.router");
const roleRouter = require("./role.router");
const dustbinRoleController = require("./dustbinRole.router");
const accountRouter = require("./account.router");
const authRouter = require("./auth.router.js");
const authMiddleware = require("../../middlewares/admin/auth.middleware.js");
module.exports = (app) => {
    const PATH_ADMIN = systemConfig.prefixAdmin;
    app.use(PATH_ADMIN + "/dashboard", authMiddleware.requireAuth, dashboardRouter);
    app.use(PATH_ADMIN + "/products", authMiddleware.requireAuth, productsRouter);
    app.use(PATH_ADMIN + "/dustbinProduct", authMiddleware.requireAuth, dustbinProductRouter);
    app.use(PATH_ADMIN + "/categorys", authMiddleware.requireAuth, categoryRouter);
    app.use(PATH_ADMIN + "/chat", authMiddleware.requireAuth, chatRouter);
    app.use(PATH_ADMIN + "/dustbin-mess", authMiddleware.requireAuth, dustbinMessRouter);
    app.use(PATH_ADMIN + "/role", authMiddleware.requireAuth, roleRouter);
    app.use(PATH_ADMIN + "/dustbinRole", authMiddleware.requireAuth, dustbinRoleController);
    app.use(PATH_ADMIN + "/account", authMiddleware.requireAuth, accountRouter);
    app.use(PATH_ADMIN + "/auth", authRouter);
};