const express = require("express");
const router = express.Router();
const controller = require("../../controllers/admin/order.controller");
router.get("/", controller.index);
router.patch("/change-multi", controller.changeMulti);
router.patch("/delete/:id", controller.deleteOrder);
router.get("/detel/:id" , controller.detelOrder);
router.get("/edit/:id", controller.viewEditOrder);
router.patch("/edit/:id" ,controller.updateInforUser);
module.exports = router;