const express = require("express");
const router = express.Router();
const controller = require("../../controllers/admin/postCategory.controller");
const cloud = require("../../middlewares/admin/cloud.middlewares");
var multer = require('multer');
var upload = multer();
router.get("/", controller.index);
router.get("/create" , controller.viewCreatePostCategory);
router.post("/create", upload.single('thumbnail'), cloud.clouldMiddlewares, controller.createPostCategory);
router.patch("/changeStatus/:id/:status" , controller.changeStatus);
router.get("/edit/:id" , controller.viewEdit);
router.patch("/edit/:id", upload.single('thumbnail'), cloud.clouldMiddlewares, controller.editPostCategory);
router.patch("/delete/:id" , controller.deletePostCategory);
router.get("/detel/:id" , controller.viewDetel);
router.get("/logUpdate/:id" , controller.viewLogUpdated);
router.patch("/change-multi" , controller.changeMulti);
module.exports = router;