const express = require("express");
const router = express.Router();
const controller = require("../../controllers/client/user.controller");
const cloud = require("../../middlewares/admin/cloud.middlewares");
var multer = require('multer');
var upload = multer();
router.get("/login", controller.loginUser);
router.get("/register", controller.register);
router.post("/register", controller.registerPost);
router.post("/login", controller.loginPost);
router.get("/logout", controller.logoutPost);
router.get("/password/forgot", controller.viewForgotPassword);
router.post("/password/forgot", controller.forgotPassword);
router.get("/password/otp", controller.viewOtp);
router.post("/password/otp", controller.otp);
router.get("/password/reset", controller.viewResetPassword);
router.post("/password/reset", controller.resetPassword);
router.get("/infor", controller.viewInforUser);
router.get("/change-infor", controller.viewChangeInfor);
router.patch("/change-infor", upload.single('avartar'), cloud.clouldMiddlewares, controller.changeInfor);
module.exports = router;